### PR TITLE
Adds in a few more parsers

### PR DESCRIPTION
**Pull request by veverkap**
This adds in parsers for 

* describe_target_health
* describe_account_limits
* describe_load_balancer_attributes
* modify_load_balancer_attributes
* register_targets
* deregister_targets

### CODE REVIEW

**Comment by gj** [comment]
Hey @fmcgeough, friendly ping on this — it would be great to get it merged in! 🙂

**Comment by fmcgeough** [comment]
@veverkap sorry. I just saw this. I'll get your work incorporated.

**Comment by fmcgeough** [comment]
Thanks so much @veverkap ! I've created a separate branch, copied in your code, tested it and merged it! I'm going to close your pull request. Let me know if what I've done presents any issues for you!

**Comment by veverkap** [comment]
great, thanks!

**Pull request closed without merging**
